CREATE TABLE IF NOT EXISTS Material (
	IDMaterial INTEGER PRIMARY KEY,
	CodigoMaterial TEXT UNIQUE,
	DescricaoMaterial TEXT UNIQUE,
	DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DataAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IsAtivo BOOLEAN DEFAULT TRUE
);