CREATE TABLE IF NOT EXISTS OrdemProducao (
	IDOrdemProducao INTEGER PRIMARY KEY,
	DataEntrega TEXT,
	CodigoOrdemProducao INTEGER UNIQUE,
	Quantidade INTEGER,
	IDCliente INTEGER,
	IDMaterial INTEGER,
	DataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DataAtualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	IsAtivo BOOLEAN DEFAULT TRUE,
	FOREIGN KEY (IDCliente) REFERENCES Cliente(IDCliente)
	FOREIGN KEY (IDMaterial) REFERENCES Cliente(IDMaterial)
);